"""Split every Phase 1 VIS row into day and night, without retraining anything.

Table 1 reports ONE `mAP@50-95` per (variant, seed), pooled over all 11,352 val
frames. That pool is 18.2% night (`pohang01`, 2,068 frames carrying 16,179 of the
105,098 val instances) -- and the night-box filter emptied every `pohang01` TRAIN
label, so those rows were trained to believe night frames contain nothing and then
scored on them with honest labels. Val labels were NEVER filtered; the asymmetry
was deliberate ("editing eval labels = self-grading").

The consequence is that each published number blends "how good is this detector"
with "how much night is in the val set", and a reader cannot separate them. This
reports the two populations separately. No training, no label change: the same 27
checkpoints, the same val list, just not pooled before reporting.

**It also tests a claim.** The argument for NOT redoing Phase 1 with restored night
labels is that the night handicap is *uniform across rows*, so the variant ranking
survives even though the absolute numbers are dragged down. That is an assertion
until the night column exists. If night AP varies materially across variants, the
handicap is not uniform, the ranking is in question, and the argument fails.
Section 3 reports the day-ranking vs pooled-ranking comparison that decides it.

Checkpoints live on the backup drive (`D:/Backup/Uncertain/phase1_benchmark/runs/`),
not in this tree -- `runs/benchmark/` holds only ablations and smoke runs. The val
list in `archive/phase1/main_2026-08-10/handback/` was verified byte-identical to
`Pohang_dataset/visible/val.txt`, so either can be used and the frame set matches
the original rows exactly.

`classes=[0]` (ship) throughout, matching the Phase 1 `main` rows.

**Control:** `--control N` re-validates N checkpoints on the FULL val set and
compares to the published `map50_95` in `results.csv`. The record says
re-validation reproduces to 2e-5; if the control does not, the day/night columns
below are not comparable to Table 1 and the run says so instead of pretending.

Nothing is written outside the new `--out` file and two new val-list yamls.

Usage:
    python scripts/slice_phase1_day_night.py --control 3
"""

from __future__ import annotations

import argparse
import csv
import logging
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "src"))
from _ideas_common import fmt, md_table, sgn, write_md          # noqa: E402

GRID = Path("D:/Backup/Uncertain/phase1_benchmark/runs")
PUBLISHED = Path("D:/Backup/Uncertain/phase1_benchmark/results.csv")
VAL_LIST = ROOT / "Pohang_dataset/visible/val.txt"
DERIVED = ROOT / "runs/derived"

NIGHT_RUN = "pohang01"
SHIP = 0


def build_lists() -> tuple[Path, Path, Path]:
    """Day-only and night-only val yamls. New filenames; nothing is overwritten."""
    rows = [l.strip() for l in VAL_LIST.read_text(encoding="utf-8").splitlines()
            if l.strip()]
    root = VAL_LIST.parent
    day, night = [], []
    for r in rows:
        p = str((root / r.lstrip("./")).resolve())
        (night if NIGHT_RUN in r else day).append(p)
    out = {}
    for tag, items in (("day", day), ("night", night), ("all", day + night)):
        lp = DERIVED / f"phase1val_{tag}.txt"
        lp.write_text("\n".join(items) + "\n", encoding="utf-8")
        yp = DERIVED / f"data_phase1val_{tag}.yaml"
        yp.write_text(
            f"# Phase 1 val, {tag} only -- generated by slice_phase1_day_night.py\n"
            f"train: {lp}\nval: {lp}\nnames:\n  0: ship\n  1: buoy\n",
            encoding="utf-8")
        out[tag] = yp
        print(f"[lists] {tag}: {len(items)} frames -> {yp.name}", flush=True)
    return out["day"], out["night"], out["all"]


def published() -> dict[str, float]:
    m = {}
    if PUBLISHED.is_file():
        with open(PUBLISHED, newline="", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                if r.get("grid") == "main":
                    try:
                        m[r["run_id"]] = float(r["map50_95"])
                    except (KeyError, ValueError):
                        pass
    return m


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--batch", type=int, default=8)
    ap.add_argument("--control", type=int, default=3,
                    help="how many checkpoints also get a FULL-val pass vs results.csv")
    ap.add_argument("--out", default="runs/eval/phase1_day_night_slice.md")
    args = ap.parse_args()
    t0 = time.time()

    import yaml
    import uqfusion.uq.gaussian    # noqa: F401  registers safe globals for unpickle
    from ultralytics import YOLO
    from ultralytics.utils import LOGGER
    LOGGER.setLevel(logging.ERROR)

    d_yaml, n_yaml, a_yaml = build_lists()
    pub = published()
    runs = sorted(p for p in GRID.glob("main_*") if (p / "weights/best.pt").is_file())
    print(f"[grid] {len(runs)} checkpoints under {GRID}", flush=True)
    assert runs, f"no main_* checkpoints under {GRID}"

    rows, ctrl_rows, recs = [], [], []
    for i, d in enumerate(runs):
        w = d / "weights/best.pt"
        try:
            imgsz = int(yaml.safe_load((d / "args.yaml").read_text())["imgsz"])
        except Exception:
            imgsz = 640
        kw = dict(imgsz=imgsz, batch=args.batch, classes=[SHIP],
                  verbose=False, plots=False, save_json=False)
        t = time.time()
        day = YOLO(str(w)).val(data=str(d_yaml), **kw).box.map
        night = YOLO(str(w)).val(data=str(n_yaml), **kw).box.map
        variant, seed = d.name.replace("main_", "").rsplit("_seed", 1)
        recs.append((d.name, variant, int(seed), float(day), float(night)))
        rows.append([variant, seed, fmt(day), fmt(night),
                     fmt(pub.get(d.name, float("nan"))),
                     sgn(float(day) - pub.get(d.name, float("nan")))])
        print(f"[{i + 1}/{len(runs)}] {d.name}: day {day:.4f}  night {night:.4f} "
              f"({time.time() - t:.0f}s)", flush=True)

        if i < args.control:
            full = YOLO(str(w)).val(data=str(a_yaml), **kw).box.map
            ref = pub.get(d.name, float("nan"))
            ctrl_rows.append([d.name, fmt(full), fmt(ref), sgn(float(full) - ref)])
            print(f"      control full-val {full:.5f} vs published {ref:.5f}",
                  flush=True)

    # ---- ranking check ----------------------------------------------------
    by_var: dict[str, list] = {}
    for _rid, v, _s, dd, nn in recs:
        by_var.setdefault(v, []).append((dd, nn))
    mean = {v: (sum(x[0] for x in a) / len(a), sum(x[1] for x in a) / len(a))
            for v, a in by_var.items()}
    day_rank = [v for v, _ in sorted(mean.items(), key=lambda kv: -kv[1][0])]
    night_rank = [v for v, _ in sorted(mean.items(), key=lambda kv: -kv[1][1])]
    pub_mean = {}
    for rid, v, _s, _d, _n in recs:
        if rid in pub:
            pub_mean.setdefault(v, []).append(pub[rid])
    pub_rank = [v for v, _ in sorted(((v, sum(a) / len(a))
                                      for v, a in pub_mean.items()),
                                     key=lambda kv: -kv[1])]
    rank_rows = [[str(i + 1), day_rank[i] if i < len(day_rank) else "-",
                  pub_rank[i] if i < len(pub_rank) else "-",
                  night_rank[i] if i < len(night_rank) else "-"]
                 for i in range(max(len(day_rank), len(pub_rank), len(night_rank)))]
    nights = [m[1] for m in mean.values()]
    spread = (max(nights) - min(nights)) if nights else float("nan")

    secs = [
        "Same 27 `main` checkpoints, same 11,352-frame val list (verified "
        "byte-identical to the archived handback copy), `classes=[0]`. **No "
        "retraining and no label change** \u2014 the two populations are simply not "
        "pooled before reporting.  \n"
        "Day = `pohang00/02/03/04` (9,284 frames). Night = `pohang01` (2,068 "
        "frames, 16,179 GT). Val labels were never filtered.",

        "## 1. Control \u2014 does a full-val pass still reproduce Table 1?\n\n"
        "If this does not reproduce, the day/night columns are not comparable to the "
        "published numbers and nothing below should be read as a correction to them.\n\n"
        + (md_table(["run", "full-val now", "published", "delta"], ctrl_rows)
           if ctrl_rows else "_No control requested._"),

        "## 2. Day and night, per row\n\n"
        "`published` is the pooled `map50_95` from `results.csv`. `day - published` "
        "is how much the pooled number was dragged down by including a population "
        "the model was trained to ignore.\n\n"
        + md_table(["variant", "seed", "day", "night", "published (pooled)",
                    "day \u2212 published"], rows),

        "## 3. Does the night handicap change the ranking?\n\n"
        "The argument against redoing Phase 1 is that the handicap is **uniform**, so "
        "the variant ranking survives. It holds only if the day ranking and the "
        "pooled ranking agree.\n\n"
        + md_table(["#", "by day AP", "by published (pooled)", "by night AP"],
                   rank_rows)
        + f"\n\nNight AP spread across variants: **{fmt(spread)}**. "
        + ("Day and pooled rankings **agree** \u2014 the handicap is uniform enough that "
           "the published selection stands."
           if day_rank == pub_rank else
           "Day and pooled rankings **DISAGREE** \u2014 the handicap is not uniform and "
           "the published variant selection is in question."),

        f"---\n\n_Generated by `scripts/slice_phase1_day_night.py` in "
        f"{time.time() - t0:.1f}s._",
    ]
    write_md(args.out, "Phase 1 VIS \u2014 day and night, unpooled", secs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
